### PR TITLE
Added facial_recognition file, updated requirements.txt and changed the template.

### PR DESCRIPTION
**Pull request by chanakya1310**

### CODE REVIEW

**Comment by L04DB4L4NC3R** [comment]
@SaurusXI review and approve the PR

**Review by SaurusXI — APPROVED** [review]
@chanakya1310 I see a lot of commented debug code in your modules. I suggest you add a `--debug` option to your CLI and put the debug code in separate sections in their files, and remove the stuff you don't need.
Also a tiny formatting thing in the README, don't wrap titles in <>. You can fix this in your next PR.

**Comment by Geek-ubaid** [comment]
> @chanakya1310 I see a lot of commented debug code in your modules. I suggest you add a `--debug` option to your CLI and put the debug code in separate sections in their files, and remove the stuff you don't need.
> Also a tiny formatting thing in the README, don't wrap titles in <>. You can fix this in your next PR.

@chanakya1310 have you noted these changes?

**Comment by chanakya1310** [comment]
@Geek-ubaid Removed the comments, please merge the Pull Request if all is good.

**Review by Geek-ubaid — APPROVED** [review]

**Pull request merged**
