### PR TITLE
Added the files for activity recognition

### PR DESCRIPTION
**Pull request by chanakya1310**
This is a pre-trained model, the model is in the google drive whose link is in the readme file, please test the model. The model can be tested on the MP4 video given in the same google drive link.

### CODE REVIEW

**Comment by chanakya1310** [comment]
The model can classify the video (16 FPS) into 400 different labels

**Review by SaurusXI — APPROVED** [review]
A few points - 
- place `requirements.txt` in the root folder
- In `directions to execute`, mention how a user can setup an environment to run the project
- Remove template fields in README that you aren't using

**Comment by chanakya1310** [comment]
@SaurusXI Bhaiya can you run download the activity recognition part and run it on your system, so that we can decide the next course of action

**Comment by chanakya1310** [comment]
You told me to make a confusion matrix but I couldn't find any validation dataset for this, and making it myself and validating 16 frames one time will be difficult.

**Pull request merged**
